### ISSUE TITLE
Breaking change in release 0.9.1 (and possibly 0.9.0)

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [ryanlintott/FrameUp#16]
When trying to use FrameUP 0.9.1 with XCode 15.3 (15E204a) on macOS 14.7 I get several build errors:

`Cannot find type 'extrenderer' in scope`
`'Layout' is not a member type of struct 'SwiftUI.Text'`
`Cannot find type 'TextProxy' in scope`

Version 0.8.0 works fine.
You should either fix this or consider bumping the major version (I had a "Up to next major version", so my build broke automatically).

**Comment by ryanlintott** [comment]
Sorry, I must have missed that issue. I'll get it fixed asap.

**Comment by tmolitor-stud-tu** [comment]
Don't worry, I've pinned the dependency to version 0.8.0 now, so there is no hurry :)

**Comment by ryanlintott** [comment]
This should be fixed in 0.9.2
Please confirm when you have a chance and I'll close this issue.

**Comment by tmolitor-stud-tu** [comment]
Yes, works like a charm :)
