### ISSUE TITLE
Swift 6 Compatibility Issue in Xcode 16.1

### ISSUE THREAD

**Issue by rnine** [ryanlintott/FrameUp#19]
The project no longer builds in Xcode 16.1 when using Swift 6. This appears to be a compatibility issue, as removing Swift 6 from the `swiftLanguageVersions` setting allows the project to build successfully.

Temporary Solution: Removing Swift 6 from the swiftLanguageVersions setting resolves the build issue. For reference, you can see the changes in my forked repository [here](https://github.com/rnine/FrameUp/commit/437f252cbfed5ea22fa72ceaa097bd37bf6b8498).

**Comment by ryanlintott** [comment]
This build issue is because of a change in SwiftUI that now shows concurrency errors if you use a variable inside alignmentGuide, which I do in TagView and TagViewForScrollView. Both of those views should be deprecated anyways so I'll have an update soon with a fix.

**Comment by MortenGregersen** [comment]
Good to hear, you are on it @ryanlintott ❤️

**Comment by ryanlintott** [comment]
Fixed in 0.9.6
