### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by aehlke** [ryanlintott/FrameUp#2]
Looks like some of this should work on max but readme says iOS only

**Comment by ryanlintott** [comment]
Many features may work on macOS but I haven't tested it yet. This is why I say iOS only. If you find macOS issues let me know.

**Comment by aehlke** [comment]
Got it, thx. I'll start w/ a PR to wrap the files in `#if os(iOS)` so it can be introduced into a multiplatform project and at least compile

**Comment by ryanlintott** [comment]
That would be great! Eventually I'd like to test and adjust to support macOS as well.

**Comment by ryanlintott** [comment]
I've updated the dev branch so it includes #if os(iOS). I still need to test some of the code and update the readme before I can push to main.

**Comment by ryanlintott** [comment]
macOS support has now been added in 0.5.0! There are a few iOS only elements like `AutoRotatingView`, `TabMenu`,`WidgetRelativeShape`, and `SmartScrollView`. The first 3 aren't really compatible but `SmartScrollView` has been excluded as it doesn't seem to work the same on macOS. I might make add macOS support to `SmartScrollView` in the future but that would be another issue so I'll close this one.

**Comment by aehlke** [comment]
Thanks very much. The Widget code looks very handy
