### ISSUE TITLE
build errors with XCode 16.2 Beta 3

### ISSUE THREAD

**Issue by nylki** [ryanlintott/FrameUp#20]
Heya,
Just a heads up: I recently tried out the newest XCode 16.2 Beta 3 and _FrameUp_ wasn't building anymore due to a couple of concurrency errors. 16.1 compiles just fine.
This happens in the freshly cloned repo in the Example App but also when using it as a dependency in another project.

![Screenshot 2024-11-28 at 15 31 48](https://github.com/user-attachments/assets/86df300c-735c-4e74-bdf7-6b13087a96fb)

**Comment by ryanlintott** [comment]
Thanks for letting me know. I'll have a look at this right away.

**Comment by ryanlintott** [comment]
I've found the issue and filed a feedback with Apple. [FB15989990](https://gist.github.com/ryanlintott/54f94bb45afebf824723847154195b75)
In the meantime I'm testing a workaround.

**Comment by nylki** [comment]
@ryanlintott  Sorry to resurrect this issue, but in the latest release notes of XCode 16 RC 2, it says something that might be relevant here:
> Fixed: .onPreferenceChange modifier's closure argument is required to be @Sendable. This might cause concurrency diagnostics that's unnecessary if the closure needs to access main actor-isolated values. This particular closure shouldn't have to be this restrictive. (145238570)

**Comment by ryanlintott** [comment]
Thanks for letting me know! I hope this is the fix I've been waiting for. I'll check it out when I get a chance.
